package com.application.constants

object GameConstantsRhymingWords {
    val rhymingWords = listOf(
        listOf("grana", "anna", "nana", "cabana", "tropicana"),
        listOf("merry", "berry", "ferry", "very", "perry"),
        listOf("borage", "storage", "forage", "courage", "porridge"),
        listOf("tapes", "shapes", "scrapes", "escapes", "landscapes"),
        listOf("beachy", "preachy", "leachy", "peachy", "breachy"),
        listOf("number", "slumber", "cucumber", "lumber", "humber"),
        listOf("parrot", "garret", "carrot", "barret", "harret"),
        listOf("leper", "stepper", "pepper", "creeper", "sleeper"),
        listOf("tomato", "potato", "plato", "fato", "dato"),
        listOf("bunions", "onions", "runions", "sponions", "lunions"),
        listOf("gallery", "celery", "smallery", "mallory", "ballery"),
        listOf("ladish", "radish", "madish", "padish", "tadish"),
        listOf("Grenada", "Canada", "Alabama", "Nevada", "Salada"),
        listOf("dance", "France", "glance", "trance", "chance"),
        listOf("grill", "Brazil", "chill", "spill", "thrill"),
        listOf("quirky", "Turkey", "murky", "perky", "jerky"),
        listOf("fleece", "Greece", "piece", "geese", "cease"),
        listOf("flexico", "Mexico", "texico", "nexico", "vexico"),
        listOf("flares", "chairs", "blares", "scares", "wares"),
        listOf("labels", "tables", "fables", "stables", "ables"),
        listOf("ouch", "couch", "pouch", "vouch", "scouch"),
        listOf("more", "floor", "door", "bore", "store"),
        listOf("terror", "mirror", "horror", "sorrow", "borrow"),
        listOf("mountains", "curtains", "fountains", "countains", "bountains"),
        listOf("proctor", "doctor", "conductor", "instructor", "protector"),
        listOf("sawyer", "lawyer", "employer", "enjoyer", "destroyer"),
        listOf("purse", "nurse", "verse", "curse", "worse"),
        listOf("charmer", "farmer", "armor", "alarmor", "harmer"),
        listOf("cartist", "artist", "smartest", "tartest", "martest"),
        listOf("fighter", "writer", "lighter", "brighter", "tighter"),
        listOf("small", "tall", "call", "hall", "wall"),
        listOf("fort", "short", "sport", "court", "sort"),
        listOf("mini", "skinny", "tinny", "ginny", "winny"),
        listOf("nervy", "curvy", "servy", "pervy", "vervy"),
        listOf("ransom", "handsome", "dansome", "lonesome", "fansom"),
        listOf("witty", "pretty", "gritty", "shitty", "pity"),
        listOf("looking", "cooking", "booking", "shooking", "hooking"),
        listOf("leading", "reading", "bleeding", "feeding", "seeding"),
        listOf("fighting", "writing", "biting", "lighting", "sighting"),
        listOf("logging", "jogging", "clogging", "fogging", "dogging"),
        listOf("prancing", "dancing", "glancing", "lancing", "chancing"),
        listOf("leaning", "cleaning", "beaning", "seeming", "teeming"),
        listOf("wealthy", "stealthy", "malthy"),
        listOf("witness", "fitness", "bitness", "sitness", "litness"),
        listOf("sloga", "boga", "foga", "poga"),
        listOf("gravel", "travel", "navel", "davel", "ravel"),
        listOf("naming", "gaming", "taming", "shaming", "flaming"),
        listOf("passion", "fashion", "ration", "lession", "session")
    )
}
