package com.application.constants

object GameConstantsRhymingWords {
    val rhymingWords = listOf(
        listOf("bandana", "savanna", "cabana", "Hannah", "Montana"),
        listOf("berry", "merry", "ferry", "very", "scary"),
        listOf("door hinge", "storage", "forage", "porridge", "courage"),
        listOf("shapes", "escapes", "scrapes", "tapes", "apes"),
        listOf("beachy", "preachy", "leachy", "screechy", "teachy"),
        listOf("encumber", "number", "plumber", "slumber", "lumber"),
        listOf("parrot", "garret", "barret", "clarit", "carot"),
        listOf("leper", "stepper", "prepper", "klepper", "wrecker"),
        listOf("tomato", "grotto", "auto", "motto", "lotto"),
        listOf("bunions", "dungeons", "champions", "companions", "scallions"),
        listOf("mystery", "gallery", "buttery", "battery", "blustery"),
        listOf("faddish", "lavish", "ravish", "banish", "vanish"),
        listOf("Panama", "Havana", "Savanna", "Indiana", "Alabama"),
        listOf("dance", "chance", "glance", "stance", "trance"),
        listOf("chill", "spill", "drill", "fill", "will"),
        listOf("jerky", "quirky", "perky", "murky", "worky"),
        listOf("fleece", "peace", "cease", "piece", "lease"),
        listOf("flexico", "texico", "lexico", "exico", "vexico"),
        listOf("stairs", "bears", "fairs", "pairs", "cares"),
        listOf("labels", "fables", "stables", "cables", "sables"),
        listOf("pouch", "vouch", "ouch", "crouch", "scouch"),
        listOf("door", "more", "bore", "core", "sore"),
        listOf("terror", "error", "bearer", "fairer", "clearer"),
        listOf("certain", "burdens", "mountains", "fountains", "obtains"),
        listOf("proctor", "conductor", "constructor", "instructor", "protector"),
        listOf("sawyer", "employer", "destroyer", "enjoyer", "loyer"),
        listOf("curse", "purse", "worse", "terse", "verse"),
        listOf("charmer", "armor", "warmer", "harmer", "former"),
        listOf("chartist", "garnist", "smartest", "harvest", "dartist"),
        listOf("fighter", "lighter", "brighter", "biter", "tighter"),
        listOf("fall", "ball", "call", "hall", "mall"),
        listOf("court", "fort", "port", "sort", "sport"),
        listOf("minnie", "tinny", "winny", "finny", "shinny"),
        listOf("nervy", "worthy", "scurvy", "dervy", "purvey"),
        listOf("ransome", "blossom", "awesome", "boredom", "freedom"),
        listOf("witty", "pity", "city", "gritty", "kitty"),
        listOf("looking", "booking", "hooking", "crooking", "shooking"),
        listOf("leading", "bleeding", "feeding", "needing", "seeding"),
        listOf("fighting", "lighting", "biting", "inviting", "sighting"),
        listOf("logging", "clogging", "blogging", "slogging", "hogging"),
        listOf("prancing", "glancing", "enhancing", "financing", "romancing"),
        listOf("leaning", "gleaning", "screening", "preening", "reigning"),
        listOf("wealthy", "stealthy", "filthy", "lengthy", "earthy"),
        listOf("witness", "greatness", "neatness", "sweetness", "brightness"),
        listOf("toga", "saga", "bodega", "omega", "coda"),
        listOf("gravel", "marvel", "unravel", "level", "novel"),
        listOf("naming", "flaming", "taming", "blaming", "framing"),
        listOf("passion", "ration", "mansion", "caption", "action")
    )
}
