package com.application.constants

object GameConstantsDescriptions {
    val descriptions = listOf(
        "A long curved fruit with a yellow skin and soft, sweet, white flesh inside.",
        "A small, round stone fruit that is typically bright or dark red.",
        "A round juicy citrus fruit with a tough bright reddish-yellow rind.",
        "Small, sweet, round, and typically purple or green fruits growing in clusters.",
        "Having a flavor or aroma like that of a peach; fruity and sweet.",
        "A long, green vegetable with a refreshing taste and high water content.",
        "A tapering orange-colored root eaten as a vegetable.",
        "A vegetable that can be red, green, yellow, or orange, with a crunchy texture.",
        "A starchy plant tuber that is a staple food in many parts of the world.",
        "A vegetable with a strong smell and flavor, composed of multiple layers.",
        "A long, fibrous stalk that is often used in salads and soups.",
        "A small, crisp root vegetable that is typically red or white.",
        "The second-largest country in the world by total area, located in North America.",
        "A country in Western Europe known for its wines, cuisine, and the Eiffel Tower.",
        "The largest country in South America, famous for its Amazon rainforest and carnival.",
        "A transcontinental country located mainly on the Anatolian Peninsula in Western Asia.",
        "A country in southeastern Europe with thousands of islands throughout the Aegean and Ionian seas.",
        "A large country in North America known for its rich cultural heritage and cuisine.",
        "Pieces of furniture designed for people to sit on, typically with four legs and a backrest.",
        "Furniture with a flat top and one or more legs, used as a surface for working or eating.",
        "A long upholstered piece of furniture for several people to sit on.",
        "The lower surface of a room, on which one stands.",
        "A reflective surface, typically of glass coated with a metal amalgam.",
        "Fabric panels that are hung on windows to block or filter light.",
        "A medical professional who diagnoses and treats illnesses and injuries.",
        "A professional who practices law, providing advice and representation in legal matters.",
        "A healthcare professional who provides care and treatment to patients.",
        "A person who operates a farm, cultivating crops and raising animals.",
        "A person who creates paintings, sculptures, or other works of art.",
        "A person who writes books, articles, or other texts.",
        "Having a greater than average height.",
        "Having less than average height.",
        "Very thin or slender.",
        "Having a full, rounded figure.",
        "Attractive in a traditionally masculine way.",
        "Attractive in a delicate, feminine way.",
        "The process of preparing food for eating.",
        "The activity or skill of making sense of written or printed matter.",
        "The act of forming letters, words, or symbols on a surface.",
        "Running at a slow, steady pace as a form of physical exercise.",
        "Moving rhythmically to music.",
        "The act of making a space clean and free from dirt.",
        "In good physical or mental condition; healthy.",
        "The condition of being physically fit and healthy.",
        "A group of physical, mental, and spiritual practices or disciplines.",
        "The activity of going to different places, often for pleasure.",
        "The action or practice of playing electronic games.",
        "A popular style or practice, especially in clothing, footwear, accessories, and makeup."
    )
}